[package]
name = "enyare-contract"
version = "0.1.0"
authors = ["tobiasruck <ruck.tobias@gmail.com>"]
edition = "2018"

[dependencies]
bitcoin-cash = { path="../../../../becash/rust/bitcoin-cash/bitcoin-cash", version="0.2.3" }
